# Slovak translations for keystone.
# Copyright (C) 2013 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version:  Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-03-26 06:00+0000\n"
"PO-Revision-Date: 2013-08-30 04:19+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Slovak "
"(http://www.transifex.com/projects/p/openstack/language/sk/)\n"
"Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: keystone/clean.py:24
#, python-format
msgid "%s cannot be empty."
msgstr ""

#: keystone/clean.py:26
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr ""

#: keystone/clean.py:31
#, python-format
msgid "%(property_name)s should not be greater than %(max_length)s characters."
msgstr ""

#: keystone/clean.py:40
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr ""

#: keystone/exception.py:49
msgid "missing exception kwargs (programmer error)"
msgstr ""

#: keystone/exception.py:79
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s. The server could not "
"comply with the request since it is either malformed or otherwise "
"incorrect. The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:88
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""

#: keystone/exception.py:97
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the "
"limit of column %(type)s(CHAR(%(length)d))."
msgstr ""

#: keystone/exception.py:103
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. "
"The server could not comply with the request because the attribute size "
"is invalid (too large). The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:113
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr ""

#: keystone/exception.py:132
msgid "The request you have made requires authentication."
msgstr ""

#: keystone/exception.py:138
msgid "Authentication plugin error."
msgstr ""

#: keystone/exception.py:146
#, python-format
msgid "Unable to find valid groups while using mapping %(mapping_id)s"
msgstr ""

#: keystone/exception.py:151
msgid "Attempted to authenticate with an unsupported method."
msgstr ""

#: keystone/exception.py:159
msgid "Additional authentications steps required."
msgstr ""

#: keystone/exception.py:167
msgid "You are not authorized to perform the requested action."
msgstr ""

#: keystone/exception.py:174
#, python-format
msgid "You are not authorized to perform the requested action, %(action)s."
msgstr ""

#: keystone/exception.py:179
#, python-format
msgid "Could not change immutable attribute %(attribute)s in target %(target)s"
msgstr ""

#: keystone/exception.py:184
#, python-format
msgid "Could not find, %(target)s."
msgstr ""

#: keystone/exception.py:190
#, python-format
msgid "Could not find endpoint, %(endpoint_id)s."
msgstr ""

#: keystone/exception.py:197
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr ""

#: keystone/exception.py:202
#, python-format
msgid "Could not find policy, %(policy_id)s."
msgstr ""

#: keystone/exception.py:206
#, python-format
msgid "Could not find role, %(role_id)s."
msgstr ""

#: keystone/exception.py:210
#, python-format
msgid "Could not find region, %(region_id)s."
msgstr ""

#: keystone/exception.py:214
#, python-format
msgid "Could not find service, %(service_id)s."
msgstr ""

#: keystone/exception.py:218
#, python-format
msgid "Could not find domain, %(domain_id)s."
msgstr ""

#: keystone/exception.py:222
#, python-format
msgid "Could not find project, %(project_id)s."
msgstr ""

#: keystone/exception.py:226
#, python-format
msgid "Could not find token, %(token_id)s."
msgstr ""

#: keystone/exception.py:230
#, python-format
msgid "Could not find user, %(user_id)s."
msgstr ""

#: keystone/exception.py:234
#, python-format
msgid "Could not find group, %(group_id)s."
msgstr ""

#: keystone/exception.py:238
#, python-format
msgid "Could not find mapping, %(mapping_id)s."
msgstr ""

#: keystone/exception.py:242
#, python-format
msgid "Could not find trust, %(trust_id)s."
msgstr ""

#: keystone/exception.py:246
#, python-format
msgid "No remaining uses for trust %(trust_id)s."
msgstr ""

#: keystone/exception.py:250
#, python-format
msgid "Could not find credential, %(credential_id)s."
msgstr ""

#: keystone/exception.py:254
#, python-format
msgid "Could not find version, %(version)s."
msgstr ""

#: keystone/exception.py:258
#, python-format
msgid "Could not find IdentityProvider, %(idp_id)s."
msgstr ""

#: keystone/exception.py:262
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for IdentityProvider, "
"%(idp_id)s"
msgstr ""

#: keystone/exception.py:267
#, python-format
msgid "Conflict occurred attempting to store %(type)s. %(details)s"
msgstr ""

#: keystone/exception.py:274
msgid "Request is too large."
msgstr ""

#: keystone/exception.py:281
msgid "An unexpected error prevented the server from fulfilling your request."
msgstr ""

#: keystone/exception.py:284
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request. "
"%(exception)s"
msgstr ""

#: keystone/exception.py:307
msgid ""
"Expected signing certificates are not available on the server. Please "
"check Keystone configuration."
msgstr ""

#: keystone/exception.py:313
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr ""

#: keystone/exception.py:318
#, python-format
msgid ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in "
"the backend."
msgstr ""

#: keystone/exception.py:323
msgid "The action you have requested has not been implemented."
msgstr ""

#: keystone/exception.py:330
msgid "The service you have requested is no longer available on this server."
msgstr ""

#: keystone/exception.py:337
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr ""

#: keystone/exception.py:343
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration "
"repository path at %(path)s doesn't exist or isn't a directory."
msgstr ""

#: keystone/notifications.py:120
#, python-format
msgid "%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr ""

#: keystone/notifications.py:129
#, python-format
msgid "Method not callable: %s"
msgstr ""

#: keystone/notifications.py:137
#, python-format
msgid "Callback: `%(callback)s` subscribed to event `%(event)s`."
msgstr ""

#: keystone/notifications.py:156
#, python-format
msgid ""
"Invoking callback %(cb_name)s for event %(service)s %(resource_type)s "
"%(operation)s for%(payload)s"
msgstr ""

#: keystone/notifications.py:219
#, python-format
msgid "Failed to send %(res_id)s %(event_type)s notification"
msgstr ""

#: keystone/notifications.py:290
#, python-format
msgid "CADF Event: %s"
msgstr ""

#: keystone/notifications.py:303
#, python-format
msgid "Failed to send %(action)s %(event_type)s notification"
msgstr ""

#: keystone/assignment/controllers.py:72
#, python-format
msgid "Authentication failed: %s"
msgstr ""

#: keystone/assignment/controllers.py:106
#: keystone/assignment/controllers.py:220 keystone/identity/controllers.py:131
msgid "Name field is required and cannot be empty"
msgstr ""

#: keystone/assignment/controllers.py:143
#, python-format
msgid "User %(user_id)s in project %(project_id)s doesn't exist."
msgstr ""

#: keystone/assignment/controllers.py:161
msgid "Marker could not be found"
msgstr ""

#: keystone/assignment/controllers.py:172
msgid "Invalid limit value"
msgstr ""

#: keystone/assignment/controllers.py:475
msgid "Specify a domain or project, not both"
msgstr ""

#: keystone/assignment/controllers.py:480
msgid "Specify a user or group, not both"
msgstr ""

#: keystone/assignment/controllers.py:694
#, python-format
msgid ""
"Group %(group)s not found for role-assignment - %(target)s with Role: "
"%(role)s"
msgstr ""

#: keystone/assignment/core.py:242
#, python-format
msgid "Creating the default role %s because it does not exist."
msgstr ""

#: keystone/assignment/core.py:274
#, python-format
msgid "Removing role %s failed because it does not exist."
msgstr ""

#: keystone/assignment/core.py:336
msgid "delete the default domain"
msgstr ""

#: keystone/assignment/core.py:347
msgid "cannot delete a domain that is enabled, please disable it first."
msgstr ""

#: keystone/assignment/core.py:384
#, python-format
msgid ""
"Project %(projectid)s not found when deleting domain contents for "
"%(domainid)s, continuing with cleanup."
msgstr ""

#: keystone/assignment/core.py:397
#, python-format
msgid ""
"Group %(groupid)s not found when deleting domain contents for "
"%(domainid)s, continuing with cleanup."
msgstr ""

#: keystone/assignment/core.py:409
#, python-format
msgid ""
"User %(userid)s not found when deleting domain contents for %(domainid)s,"
" continuing with cleanup."
msgstr ""

#: keystone/assignment/core.py:521
#, python-format
msgid "Group %s not found, no tokens to invalidate."
msgstr ""

#: keystone/assignment/core.py:559
#, python-format
msgid "Project (%s)"
msgstr ""

#: keystone/assignment/core.py:561
#, python-format
msgid "Domain (%s)"
msgstr ""

#: keystone/assignment/core.py:563
msgid "Unknown Target"
msgstr ""

#: keystone/assignment/core.py:564
#, python-format
msgid ""
"Group (%(group)s), referenced in assignment for %(target)s, not found - "
"ignoring."
msgstr ""

#: keystone/assignment/core.py:1005 keystone/common/controller.py:269
#: keystone/identity/core.py:232
#, python-format
msgid "Expected dict or list: %s"
msgstr ""

#: keystone/assignment/backends/kvs.py:202
#: keystone/assignment/backends/ldap.py:581
#: keystone/assignment/backends/sql.py:353
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr ""

#: keystone/assignment/backends/ldap.py:111
msgid "Domain metadata not supported by LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:200
#: keystone/assignment/backends/ldap.py:248 keystone/common/ldap/core.py:334
#: keystone/identity/backends/kvs.py:117 keystone/identity/backends/kvs.py:224
#, python-format
msgid "Duplicate ID, %s."
msgstr ""

#: keystone/assignment/backends/ldap.py:208 keystone/common/ldap/core.py:324
#: keystone/identity/backends/kvs.py:125 keystone/identity/backends/kvs.py:152
#: keystone/identity/backends/kvs.py:231 keystone/identity/backends/kvs.py:259
#, python-format
msgid "Duplicate name, %s."
msgstr ""

#: keystone/assignment/backends/ldap.py:250
#: keystone/assignment/backends/ldap.py:258
#: keystone/assignment/backends/ldap.py:262
msgid "Domains are read-only against LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:315
#: keystone/assignment/backends/sql.py:137
msgid "Inherited roles can only be assigned to domains"
msgstr ""

#: keystone/assignment/backends/ldap.py:554
#, python-format
msgid "User %(user_id)s already has role %(role_id)s in tenant %(tenant_id)s"
msgstr ""

#: keystone/assignment/backends/ldap.py:560
#, python-format
msgid "Role %s not found"
msgstr ""

#: keystone/assignment/backends/ldap.py:667
#, python-format
msgid "Cannot duplicate name %s"
msgstr ""

#: keystone/assignment/backends/sql.py:124
#, python-format
msgid ""
"Unexpected combination of grant attributes - User, Group, Project, "
"Domain: %s"
msgstr ""

#: keystone/assignment/backends/sql.py:293
msgid "Must specify either domain or project"
msgstr ""

#: keystone/assignment/backends/sql.py:374
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr ""

#: keystone/auth/controllers.py:57
#, python-format
msgid ""
"Cannot load an auth-plugin by class-name without a \"method\" attribute "
"defined: %s"
msgstr ""

#: keystone/auth/controllers.py:65
#, python-format
msgid "Driver requested method %(req)s does not match plugin name %(plugin)s."
msgstr ""

#: keystone/auth/controllers.py:70
#, python-format
msgid "Auth Plugin %s does not have a \"method\" attribute."
msgstr ""

#: keystone/auth/controllers.py:74
#, python-format
msgid ""
"Auth plugin %(plugin)s is requesting previously registered method "
"%(method)s"
msgstr ""

#: keystone/auth/controllers.py:115
#, python-format
msgid "Project is disabled: %s"
msgstr ""

#: keystone/auth/controllers.py:121 keystone/auth/plugins/password.py:41
#: keystone/token/core.py:80 keystone/token/core.py:96
#, python-format
msgid "Domain is disabled: %s"
msgstr ""

#: keystone/auth/controllers.py:278
msgid "Scoping to both domain and project is not allowed"
msgstr ""

#: keystone/auth/controllers.py:281
msgid "Scoping to both domain and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:284
msgid "Scoping to both project and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:380
#, python-format
msgid ""
"User %(user_id)s doesn't have access to default project %(project_id)s. "
"The token will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:387
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s is disabled. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:396
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s not found. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:427
msgid "User not found"
msgstr ""

#: keystone/auth/plugins/external.py:46
msgid "No authenticated user"
msgstr ""

#: keystone/auth/plugins/external.py:56
#, python-format
msgid "Unable to lookup user %s"
msgstr ""

#: keystone/auth/plugins/oauth1.py:38
#, python-format
msgid "%s not supported"
msgstr ""

#: keystone/auth/plugins/oauth1.py:56
msgid "Access token is expired"
msgstr ""

#: keystone/auth/plugins/oauth1.py:70
msgid "Could not validate the access token"
msgstr ""

#: keystone/auth/plugins/password.py:47 keystone/token/core.py:72
#, python-format
msgid "User is disabled: %s"
msgstr ""

#: keystone/auth/plugins/password.py:123
msgid "Invalid username or password"
msgstr ""

#: keystone/auth/plugins/saml2.py:95
msgid "Federation token is expired"
msgstr ""

#: keystone/catalog/controllers.py:154
#, python-format
msgid "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""
msgstr ""

#: keystone/catalog/controllers.py:206 keystone/catalog/controllers.py:265
#: keystone/identity/controllers.py:134
msgid "Enabled field must be a boolean"
msgstr ""

#: keystone/catalog/core.py:42
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr ""

#: keystone/catalog/core.py:47
#, python-format
msgid ""
"Malformed endpoint %(url)s - unknown key %(keyerror)s(are you missing "
"brackets ?)"
msgstr ""

#: keystone/catalog/core.py:53
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type "
"notifier ?)"
msgstr ""

#: keystone/catalog/backends/templated.py:106
#, python-format
msgid "Unable to open template file %s"
msgstr ""

#: keystone/common/authorization.py:75
msgid "RBAC: Invalid user data in v3 token"
msgstr ""

#: keystone/common/authorization.py:80
msgid "RBAC: Proceeding without project"
msgstr ""

#: keystone/common/authorization.py:99
msgid "RBAC: Invalid user data in v2 token"
msgstr ""

#: keystone/common/authorization.py:104
msgid "RBAC: Proceeding without tenant"
msgstr ""

#: keystone/common/base64utils.py:205 keystone/common/base64utils.py:278
#: keystone/common/base64utils.py:332
msgid "pad must be single character"
msgstr ""

#: keystone/common/base64utils.py:211
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before 2nd to last char"
msgstr ""

#: keystone/common/base64utils.py:215
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before non-pad last char"
msgstr ""

#: keystone/common/base64utils.py:221
#, python-format
msgid "text is not a multiple of 4, but contains pad \"%s\""
msgstr ""

#: keystone/common/base64utils.py:240 keystone/common/base64utils.py:261
msgid "padded base64url text must be multiple of 4 characters"
msgstr ""

#: keystone/common/controller.py:39
#, python-format
msgid "RBAC: Authorizing %(action)s(%(kwargs)s)"
msgstr ""

#: keystone/common/controller.py:46
msgid "RBAC: using auth context from the request environment"
msgstr ""

#: keystone/common/controller.py:51
msgid "RBAC: building auth context from the incoming auth token"
msgstr ""

#: keystone/common/controller.py:62 keystone/middleware/core.py:266
msgid "RBAC: Invalid token"
msgstr ""

#: keystone/common/controller.py:91 keystone/common/controller.py:182
#: keystone/common/controller.py:585
msgid "RBAC: Bypassing authorization"
msgstr ""

#: keystone/common/controller.py:138 keystone/common/controller.py:180
#: keystone/common/controller.py:603
msgid "RBAC: Authorization granted"
msgstr ""

#: keystone/common/controller.py:168
#, python-format
msgid "RBAC: Adding query filter params (%s)"
msgstr ""

#: keystone/common/controller.py:532
msgid "Cannot change Domain ID"
msgstr ""

#: keystone/common/controller.py:556
msgid "Invalid token in _get_domain_id_for_request"
msgstr ""

#: keystone/common/dependency.py:83
msgid "event_callbacks must be a dict"
msgstr ""

#: keystone/common/dependency.py:88
#, python-format
msgid "event_callbacks[%s] must be a dict"
msgstr ""

#: keystone/common/pemutils.py:223
#, python-format
msgid "unknown pem_type \"%(pem_type)s\", valid types are: %(valid_pem_types)s"
msgstr ""

#: keystone/common/pemutils.py:242
#, python-format
msgid ""
"unknown pem header \"%(pem_header)s\", valid headers are: "
"%(valid_pem_headers)s"
msgstr ""

#: keystone/common/pemutils.py:300
#, python-format
msgid "failed to find end matching \"%s\""
msgstr ""

#: keystone/common/pemutils.py:304
#, python-format
msgid ""
"beginning & end PEM headers do not match (%(begin_pem_header)s!= "
"%(end_pem_header)s)"
msgstr ""

#: keystone/common/pemutils.py:379
#, python-format
msgid "unknown pem_type: \"%s\""
msgstr ""

#: keystone/common/pemutils.py:391
#, python-format
msgid ""
"failed to base64 decode %(pem_type)s PEM at position%(position)d: "
"%(err_msg)s"
msgstr ""

#: keystone/common/serializer.py:203
msgid "Multiple truncation attributes found"
msgstr ""

#: keystone/common/utils.py:77
#, python-format
msgid "Truncating user password to %s characters."
msgstr ""

#: keystone/common/utils.py:195 keystone/credential/controllers.py:42
msgid "Invalid blob in credential"
msgstr ""

#: keystone/common/utils.py:274
msgid ""
"Error setting up the debug environment. Verify that the option --debug-"
"url has the format <host>:<port> and that a debugger processes is "
"listening on that port."
msgstr ""

#: keystone/common/wsgi.py:67
msgid "No bind information present in token"
msgstr ""

#: keystone/common/wsgi.py:71
#, python-format
msgid "Named bind mode %s not in bind information"
msgstr ""

#: keystone/common/wsgi.py:78
msgid "Kerberos credentials required and not present"
msgstr ""

#: keystone/common/wsgi.py:82
msgid "Kerberos credentials do not match those in bind"
msgstr ""

#: keystone/common/wsgi.py:85
msgid "Kerberos bind authentication successful"
msgstr ""

#: keystone/common/wsgi.py:88
#, python-format
msgid "Ignoring unknown bind for permissive mode: {%(bind_type)s: %(identifier)s}"
msgstr ""

#: keystone/common/wsgi.py:92
#, python-format
msgid "Couldn't verify unknown bind: {%(bind_type)s: %(identifier)s}"
msgstr ""

#: keystone/common/wsgi.py:181
#, python-format
msgid "arg_dict: %s"
msgstr ""

#: keystone/common/wsgi.py:210
#, python-format
msgid "Authorization failed. %(exception)s from %(remote_addr)s"
msgstr ""

#: keystone/common/wsgi.py:287
#, python-format
msgid "%s field is required and cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:298
msgid ""
"will not lookup trust as the request auth token is either absent or it is"
" the system admin token"
msgstr ""

#: keystone/common/wsgi.py:305
msgid "Invalid token in _get_trust_id_for_request"
msgstr ""

#: keystone/common/wsgi.py:501 keystone/tests/test_wsgi.py:274
msgid "The resource could not be found."
msgstr ""

#: keystone/common/cache/core.py:54
#, python-format
msgid "CACHE_GET: Key: \"%(key)r\" Value: \"%(value)r\""
msgstr ""

#: keystone/common/cache/core.py:60
#, python-format
msgid "CACHE_GET_MULTI: \"%(keys)r\" Values: \"%(values)r\""
msgstr ""

#: keystone/common/cache/core.py:65
#, python-format
msgid "CACHE_SET: Key: \"%(key)r\" Value: \"%(value)r\""
msgstr ""

#: keystone/common/cache/core.py:70
#, python-format
msgid "CACHE_SET_MULTI: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:75
#, python-format
msgid "CACHE_DELETE: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:78
#, python-format
msgid "CACHE_DELETE_MULTI: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:96
#, python-format
msgid ""
"Unable to build cache config-key. Expected format \"<argname>:<value>\". "
"Skipping unknown format: %s"
msgstr ""

#: keystone/common/cache/core.py:104
#, python-format
msgid "Keystone Cache Config: %s"
msgstr ""

#: keystone/common/cache/core.py:119
msgid "region not type dogpile.cache.CacheRegion"
msgstr ""

#: keystone/common/cache/core.py:152
#, python-format
msgid "Adding cache-proxy '%s' to backend."
msgstr ""

#: keystone/common/cache/backends/mongo.py:231
msgid "db_hosts value is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:236
msgid "database db_name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:241
msgid "cache_collection name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:252
msgid "integer value expected for w (write concern attribute)"
msgstr ""

#: keystone/common/cache/backends/mongo.py:260
msgid "replicaset_name required when use_replica is True"
msgstr ""

#: keystone/common/cache/backends/mongo.py:275
msgid "integer value expected for mongo_ttl_seconds"
msgstr ""

#: keystone/common/cache/backends/mongo.py:301
msgid "no ssl support available"
msgstr ""

#: keystone/common/cache/backends/mongo.py:310
#, python-format
msgid ""
"Invalid ssl_cert_reqs value of %s, must be one of \"NONE\", \"OPTIONAL\","
" \"REQUIRED\""
msgstr ""

#: keystone/common/cache/backends/mongo.py:403
#, python-format
msgid ""
"TTL index already exists on db collection <%(c_name)s>, remove index "
"<%(indx_name)s> first to make updated mongo_ttl_seconds value to be  "
"effective"
msgstr ""

#: keystone/common/environment/__init__.py:52
#, python-format
msgid "Environment configured as: %s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:52
#, python-format
msgid "Starting %(arg0)s on %(host)s:%(port)s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:123
msgid "Server error"
msgstr ""

#: keystone/common/kvs/core.py:63
#, python-format
msgid "Registering Dogpile Backend %(backend_path)s as %(backend_name)s"
msgstr ""

#: keystone/common/kvs/core.py:71
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:106
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr ""

#: keystone/common/kvs/core.py:122
#, python-format
msgid "Importing class %s as KVS proxy."
msgstr ""

#: keystone/common/kvs/core.py:130
#, python-format
msgid "%s is not a dogpile.proxy.ProxyBackend"
msgstr ""

#: keystone/common/kvs/core.py:134
#, python-format
msgid "Adding proxy '%(proxy)s' to KVS %(name)s."
msgstr ""

#: keystone/common/kvs/core.py:141
#, python-format
msgid "Key Value Store not configured: %s"
msgstr ""

#: keystone/common/kvs/core.py:158
#, python-format
msgid ""
"Non-expiring keys not supported/required by %(region)s backend; unable to"
" set key_mangler for backend: %(err)s"
msgstr ""

#: keystone/common/kvs/core.py:184
#, python-format
msgid "Using %(func)s as KVS region %(name)s key_mangler"
msgstr ""

#: keystone/common/kvs/core.py:194
msgid "`key_mangler` option must be a function reference"
msgstr ""

#: keystone/common/kvs/core.py:196
#, python-format
msgid "Using default dogpile sha1_mangle_key as KVS region %s key_mangler"
msgstr ""

#: keystone/common/kvs/core.py:206
#, python-format
msgid "KVS region %s key_mangler disabled."
msgstr ""

#: keystone/common/kvs/core.py:235
#, python-format
msgid "KVS region configuration for %(name)s: %(config)r"
msgstr ""

#: keystone/common/kvs/core.py:348
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:352
msgid "Must be called within an active lock context."
msgstr ""

#: keystone/common/kvs/core.py:376
#, python-format
msgid "KVS lock acquired for: %s"
msgstr ""

#: keystone/common/kvs/core.py:395
#, python-format
msgid "KVS lock released for: %s"
msgstr ""

#: keystone/common/kvs/core.py:397
#, python-format
msgid "KVS lock released (timeout reached) for: %s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:72
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:111
#, python-format
msgid ""
"Backend `%(driver)s` is not a valid memcached backend. Valid drivers: "
"%(driver_list)s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:182
msgid "`key_mangler` functions must be callable."
msgstr ""

#: keystone/common/ldap/core.py:77
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:87
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:99
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:216
#, python-format
msgid ""
"Invalid additional attribute mapping: \"%s\". Format must be "
"<ldap_attribute>:<keystone_attribute>"
msgstr ""

#: keystone/common/ldap/core.py:222
#, python-format
msgid ""
"Invalid additional attribute mapping: \"%(item)s\". Value "
"\"%(attr_map)s\" must use one of %(keys)s."
msgstr ""

#: keystone/common/ldap/core.py:303
#, python-format
msgid "LDAP %s create"
msgstr ""

#: keystone/common/ldap/core.py:308
#, python-format
msgid "LDAP %s update"
msgstr ""

#: keystone/common/ldap/core.py:313
#, python-format
msgid "LDAP %s delete"
msgstr ""

#: keystone/common/ldap/core.py:434
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr ""

#: keystone/common/ldap/core.py:491
#, python-format
msgid "LDAP init: url=%s"
msgstr ""

#: keystone/common/ldap/core.py:492
#, python-format
msgid ""
"LDAP init: use_tls=%(use_tls)s\n"
"tls_cacertfile=%(tls_cacertfile)s\n"
"tls_cacertdir=%(tls_cacertdir)s\n"
"tls_req_cert=%(tls_req_cert)s\n"
"tls_avail=%(tls_avail)s\n"
msgstr ""

#: keystone/common/ldap/core.py:511
msgid "Invalid TLS / LDAPS combination"
msgstr ""

#: keystone/common/ldap/core.py:515
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr ""

#: keystone/common/ldap/core.py:525
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr ""

#: keystone/common/ldap/core.py:537
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr ""

#: keystone/common/ldap/core.py:544
#, python-format
msgid "LDAP TLS: invalid TLS_REQUIRE_CERT Option=%s"
msgstr ""

#: keystone/common/ldap/core.py:561
#, python-format
msgid "LDAP bind: dn=%s"
msgstr ""

#: keystone/common/ldap/core.py:575
#, python-format
msgid "LDAP add: dn=%(dn)s, attrs=%(attrs)s"
msgstr ""

#: keystone/common/ldap/core.py:586
#, python-format
msgid ""
"LDAP search: dn=%(dn)s, scope=%(scope)s, query=%(query)s, "
"attrs=%(attrlist)s"
msgstr ""

#: keystone/common/ldap/core.py:610
msgid ""
"Referrals were returned and ignored. Enable referral chasing in "
"keystone.conf via [ldap] chase_referrals"
msgstr ""

#: keystone/common/ldap/core.py:650
msgid ""
"LDAP Server does not support paging. Disable paging in keystone.conf to "
"avoid this message."
msgstr ""

#: keystone/common/ldap/core.py:666
#, python-format
msgid "LDAP modify: dn=%(dn)s, modlist=%(modlist)s"
msgstr ""

#: keystone/common/ldap/core.py:672
#, python-format
msgid "LDAP delete: dn=%s"
msgstr ""

#: keystone/common/ldap/core.py:677
#, python-format
msgid "LDAP delete_ext: dn=%(dn)s, serverctrls=%(serverctrls)s"
msgstr ""

#: keystone/common/sql/core.py:219
msgid ""
"Cannot truncate a driver call without hints list as first parameter after"
" self "
msgstr ""

#: keystone/common/sql/migration_helpers.py:125
#: keystone/common/sql/migration_helpers.py:150
#, python-format
msgid "%s extension does not exist."
msgstr ""

#: keystone/common/sql/migrate_repo/versions/033_migrate_ec2credentials_table_credentials.py:60
#, python-format
msgid ""
"Credential %(access)s already exists with different secret in %(table)s "
"table"
msgstr ""

#: keystone/common/sql/migrate_repo/versions/033_migrate_ec2credentials_table_credentials.py:70
#, python-format
msgid ""
"Credential %(access)s already exists with different project in %(table)s "
"table"
msgstr ""

#: keystone/contrib/ec2/controllers.py:305
msgid "Token belongs to another user"
msgstr ""

#: keystone/contrib/ec2/controllers.py:333
msgid "Credential belongs to another user"
msgstr ""

#: keystone/contrib/endpoint_filter/backends/sql.py:54
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr ""

#: keystone/contrib/example/core.py:64 keystone/contrib/example/core.py:73
#, python-format
msgid ""
"Received the following notification: service %(service)s, resource_type: "
"%(resource_type)s, operation %(operation)s payload %(payload)s"
msgstr ""

#: keystone/contrib/federation/utils.py:198
msgid "Could not map user"
msgstr ""

#: keystone/contrib/federation/utils.py:227
#, python-format
msgid "Ignoring user name %s"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:79
msgid "Cannot change consumer secret"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:153
#: keystone/contrib/oauth1/backends/sql.py:285
msgid "User IDs do not match"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:160
msgid "Could not find role"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:203
msgid "Invalid signature"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:252
#: keystone/contrib/oauth1/controllers.py:322
msgid "Request token is expired"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:266
msgid "There should not be any non-oauth parameters"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:270
msgid "provided consumer key does not match stored consumer key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:274
msgid "provided verifier does not match stored verifier"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:278
msgid "provided request key does not match stored request key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:282
msgid "Request Token does not have an authorizing user id"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:338
msgid "authorizing user does not have role required"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:353
msgid "User is not a member of the requested project"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:95
msgid "Consumer not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:199
msgid "Request token not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:265
msgid "Access token not found"
msgstr ""

#: keystone/contrib/revoke/controllers.py:32
#, python-format
msgid "invalid date format %s"
msgstr ""

#: keystone/contrib/revoke/core.py:173 keystone/token/provider.py:125
#: keystone/token/provider.py:146 keystone/token/provider.py:224
#: keystone/token/provider.py:231 keystone/token/providers/common.py:624
msgid "Failed to validate token"
msgstr ""

#: keystone/credential/core.py:120
#, python-format
msgid "Deletion of credential is not required: %s"
msgstr ""

#: keystone/identity/controllers.py:161
msgid "Enabled field should be a boolean"
msgstr ""

#: keystone/identity/controllers.py:202
#, python-format
msgid "Unable to remove user %(user)s from %(tenant)s."
msgstr ""

#: keystone/identity/controllers.py:221
#, python-format
msgid "Unable to add user %(user)s to %(tenant)s."
msgstr ""

#: keystone/identity/core.py:105
#, python-format
msgid "Invalid domain name (%s) found in config file name"
msgstr ""

#: keystone/identity/core.py:129
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr ""

#: keystone/identity/core.py:142
#, python-format
msgid "Ignoring file (%s) while scanning domain config directory"
msgstr ""

#: keystone/identity/core.py:183
msgid ""
"Running an experimental and unsupported configuration "
"(domain_specific_drivers_enabled = True); this will result in known "
"issues."
msgstr ""

#: keystone/identity/backends/kvs.py:72 keystone/identity/backends/kvs.py:74
#: keystone/identity/backends/ldap.py:57 keystone/identity/backends/ldap.py:59
#: keystone/identity/backends/ldap.py:65 keystone/identity/backends/ldap.py:67
#: keystone/identity/backends/sql.py:112 keystone/identity/backends/sql.py:114
msgid "Invalid user / password"
msgstr ""

#: keystone/identity/backends/kvs.py:178 keystone/identity/backends/kvs.py:187
#: keystone/identity/backends/sql.py:198 keystone/identity/backends/sql.py:209
msgid "User not found in group"
msgstr ""

#: keystone/identity/backends/ldap.py:96 keystone/identity/backends/sql.py:160
msgid "Cannot change user ID"
msgstr ""

#: keystone/identity/backends/ldap.py:99
msgid "Cannot change user name"
msgstr ""

#: keystone/identity/backends/ldap.py:167
#, python-format
msgid ""
"Group member '%(user_dn)s' not found in '%(group_id)s'. The user should "
"be removed from the group. The user will be ignored."
msgstr ""

#: keystone/identity/backends/ldap.py:308
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr ""

#: keystone/middleware/core.py:271
msgid "Auth token not in the request header. Will not build auth context."
msgstr ""

#: keystone/middleware/core.py:276
msgid "Auth context already exists in the request environment"
msgstr ""

#: keystone/middleware/core.py:281
#, python-format
msgid "RBAC: auth_context: %s"
msgstr ""

#: keystone/openstack/common/eventlet_backdoor.py:140
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr ""

#: keystone/openstack/common/exception.py:103
msgid "Uncaught exception"
msgstr ""

#: keystone/openstack/common/excutils.py:62
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: keystone/openstack/common/excutils.py:91
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: keystone/openstack/common/fileutils.py:63
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: keystone/openstack/common/gettextutils.py:297
msgid "Message objects do not support addition."
msgstr ""

#: keystone/openstack/common/gettextutils.py:306
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: keystone/openstack/common/lockutils.py:103
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: keystone/openstack/common/lockutils.py:168
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: keystone/openstack/common/lockutils.py:177
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr ""

#: keystone/openstack/common/lockutils.py:187
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: keystone/openstack/common/lockutils.py:205
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: keystone/openstack/common/lockutils.py:209
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: keystone/openstack/common/lockutils.py:247
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: keystone/openstack/common/lockutils.py:251
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: keystone/openstack/common/log.py:326
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: keystone/openstack/common/log.py:437
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: keystone/openstack/common/log.py:488
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: keystone/openstack/common/log.py:709
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: keystone/openstack/common/loopingcall.py:82
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: keystone/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr ""

#: keystone/openstack/common/loopingcall.py:129
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: keystone/openstack/common/loopingcall.py:136
msgid "in dynamic looping call"
msgstr ""

#: keystone/openstack/common/policy.py:75
msgid "JSON file containing policy"
msgstr ""

#: keystone/openstack/common/policy.py:78
msgid "Rule enforced when requested rule is not found"
msgstr ""

#: keystone/openstack/common/policy.py:92
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: keystone/openstack/common/policy.py:182
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: keystone/openstack/common/policy.py:212
msgid "Rules successfully reloaded"
msgstr ""

#: keystone/openstack/common/policy.py:258
#, python-format
msgid "Rule %s will be now enforced"
msgstr ""

#: keystone/openstack/common/policy.py:273
#, python-format
msgid "Rule [%s] doesn't exist"
msgstr ""

#: keystone/openstack/common/policy.py:481
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: keystone/openstack/common/policy.py:491
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: keystone/openstack/common/policy.py:761
#, python-format
msgid "Failed to understand rule %r"
msgstr ""

#: keystone/openstack/common/processutils.py:130
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: keystone/openstack/common/processutils.py:145
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: keystone/openstack/common/processutils.py:169
#: keystone/openstack/common/processutils.py:241
#, python-format
msgid "Result was %s"
msgstr ""

#: keystone/openstack/common/processutils.py:181
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: keystone/openstack/common/processutils.py:220
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: keystone/openstack/common/processutils.py:222
msgid "Environment not supported over SSH"
msgstr ""

#: keystone/openstack/common/processutils.py:226
msgid "process_input not supported over SSH"
msgstr ""

#: keystone/openstack/common/service.py:134
#: keystone/openstack/common/service.py:346
msgid "Full set of CONF:"
msgstr ""

#: keystone/openstack/common/service.py:143
#: keystone/openstack/common/service.py:231
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: keystone/openstack/common/service.py:155
msgid "Exception during rpc cleanup."
msgstr ""

#: keystone/openstack/common/service.py:200
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: keystone/openstack/common/service.py:237
msgid "Unhandled exception"
msgstr ""

#: keystone/openstack/common/service.py:270
msgid "Forking too fast, sleeping"
msgstr ""

#: keystone/openstack/common/service.py:289
#, python-format
msgid "Started child %d"
msgstr ""

#: keystone/openstack/common/service.py:299
#, python-format
msgid "Starting %d workers"
msgstr ""

#: keystone/openstack/common/service.py:316
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: keystone/openstack/common/service.py:320
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: keystone/openstack/common/service.py:324
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: keystone/openstack/common/service.py:354
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: keystone/openstack/common/service.py:372
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: keystone/openstack/common/strutils.py:86
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: keystone/openstack/common/strutils.py:188
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: keystone/openstack/common/strutils.py:195
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: keystone/openstack/common/versionutils.py:69
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: keystone/openstack/common/versionutils.py:73
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: keystone/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/migration.py:188
msgid "version should be an integer"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/migration.py:216
#, python-format
msgid ""
"Tables \"%s\" have non utf8 collation, please make sure all tables are "
"CHARSET=utf8"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/migration.py:240
msgid ""
"The database is not under version control, but has tables. Please stamp "
"the current version of the schema manually."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:58
msgid "Sort key supplied was not valid."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:119
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:162
#, python-format
msgid ""
"There is no `deleted` column in `%s` table. Project doesn't use soft-"
"deleted feature."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:174
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:181
#, python-format
msgid "There is no `project_id` column in `%s` table."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:243
msgid "model should be a subclass of ModelBase"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:286
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:292
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:400
msgid "Unsupported id columns type"
msgstr ""

#: keystone/policy/backends/rules.py:99
#, python-format
msgid "enforce %(action)s: %(credentials)s"
msgstr ""

#: keystone/tests/core.py:162
#, python-format
msgid "Failed to checkout %s"
msgstr ""

#: keystone/tests/fakeldap.py:250
#, python-format
msgid "FakeLdap delete item: dn=%s"
msgstr ""

#: keystone/token/controllers.py:363
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr ""

#: keystone/token/controllers.py:380 keystone/token/controllers.py:383
msgid "Token does not belong to specified tenant."
msgstr ""

#: keystone/token/core.py:87
#, python-format
msgid "Tenant is disabled: %s"
msgstr ""

#: keystone/token/provider.py:88
msgid ""
"keystone.conf [signing] token_format (deprecated) conflicts with "
"keystone.conf [token] provider"
msgstr ""

#: keystone/token/provider.py:96
msgid ""
"keystone.conf [signing] token_format is deprecated in favor of "
"keystone.conf [token] provider"
msgstr ""

#: keystone/token/provider.py:106
msgid ""
"Unrecognized keystone.conf [signing] token_format: expected either 'UUID'"
" or 'PKI'"
msgstr ""

#: keystone/token/provider.py:222
#, python-format
msgid "Unexpected error or malformed token determining token expiry: %s"
msgstr ""

#: keystone/token/backends/kvs.py:56
msgid ""
"It is recommended to only use the base key-value-store implementation for"
" the token driver for testing purposes.  Please use "
"keystone.token.backends.memcache.Token or "
"keystone.token.backends.sql.Token instead."
msgstr ""

#: keystone/token/backends/kvs.py:131
#, python-format
msgid "Unknown token version %s"
msgstr ""

#: keystone/token/backends/kvs.py:170
#, python-format
msgid "Token `%(token_id)s` is expired, removing from `%(user_key)s`."
msgstr ""

#: keystone/token/backends/kvs.py:179
#, python-format
msgid "Token `%(token_id)s` is revoked, removing from `%(user_key)s`."
msgstr ""

#: keystone/token/backends/kvs.py:204
#, python-format
msgid "Token `%s` is expired, not adding to the revocation list."
msgstr ""

#: keystone/token/backends/kvs.py:224
#, python-format
msgid ""
"Reinitializing revocation list due to error in loading revocation list "
"from backend.  Expected `list` type got `%(type)s`. Old revocation list "
"data: %(list)r"
msgstr ""

#: keystone/token/backends/kvs.py:238
#, python-format
msgid ""
"Removing `%s` from revocation list due to invalid expires data in "
"revocation list."
msgstr ""

#: keystone/token/backends/kvs.py:269
#, python-format
msgid ""
"Invalid token entry expected tuple of `(<token_id>, <expires>)` got: "
"`%(item)r`"
msgstr ""

#: keystone/token/backends/kvs.py:278
#, python-format
msgid "Invalid expires time on token `%(token_id)s`: %(expires)r"
msgstr ""

#: keystone/token/providers/common.py:183
#: keystone/token/providers/common.py:286
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr ""

#: keystone/token/providers/common.py:188
#: keystone/token/providers/common.py:291
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr ""

#: keystone/token/providers/common.py:213
msgid "Trustor is disabled."
msgstr ""

#: keystone/token/providers/common.py:277
msgid "Trustee has no delegated roles."
msgstr ""

#: keystone/token/providers/common.py:341
msgid "User is not a trustee."
msgstr ""

#: keystone/token/providers/common.py:436
msgid "Oauth is disabled."
msgstr ""

#: keystone/token/providers/common.py:549
msgid "Non-default domain is not supported"
msgstr ""

#: keystone/token/providers/common.py:557
msgid "Domain scoped token is not supported"
msgstr ""

#: keystone/token/providers/pki.py:42
msgid "Unable to sign token"
msgstr ""

#: keystone/token/providers/pki.py:43
msgid "Unable to sign token."
msgstr ""

#: keystone/trust/controllers.py:140
msgid "At least one role should be specified."
msgstr ""

#: keystone/trust/core.py:58
msgid "remaining_uses must be a positive integer or null."
msgstr ""

