# French translations for oslo.vmware.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the oslo.vmware
# project.
#
# Translators:
# Maxime COQUEREL <max.coquerel@gmail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version:  oslo.vmware\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-11-02 06:08+0000\n"
"PO-Revision-Date: 2014-11-01 12:17+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: French "
"(http://www.transifex.com/projects/p/oslovmware/language/fr/)\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: oslo/vmware/api.py:316
#, python-format
msgid ""
"Current session: %(session)s is inactive; re-creating the session while "
"invoking method %(module)s.%(method)s."
msgstr ""
"Session courante: %(session)s est inactive; recréation de la session en "
"invoquant la méthode %(module)s.%(method)s."

#: oslo/vmware/api.py:471
#, python-format
msgid "Lease: %(lease)s is in error state. Details: %(error_msg)s."
msgstr "Bail: %(lease)s est dans une erreur de status. Détails: %(error_msg)s."

#: oslo/vmware/api.py:478
#, python-format
msgid "Unknown state: %(state)s for lease: %(lease)s."
msgstr "Statut inconnu: %(state)s for lease: %(lease)s."

#: oslo/vmware/exceptions.py:50
msgid "exception_summary must not be a list"
msgstr "exception_summary ne doit pas etre une liste"

#: oslo/vmware/exceptions.py:89
msgid "fault_list must be a list"
msgstr "fault_list doit etre une liste"

#: oslo/vmware/exceptions.py:91
msgid "details must be a dict"
msgstr "details doit etre un dict"

#: oslo/vmware/exceptions.py:121
msgid "An unknown exception occurred."
msgstr "Une exception inconnue s'est produite "

#: oslo/vmware/exceptions.py:147
msgid "VMware Driver configuration fault."
msgstr "Redirection de la configuration du pilote VMware."

#: oslo/vmware/exceptions.py:151
msgid "No default value for use_linked_clone found."
msgstr "Pas de valeur par défaut pour use_linked_clone trouvé."

#: oslo/vmware/exceptions.py:155
#, python-format
msgid "Missing parameter : %(param)s"
msgstr "Paramètre manquant : %(param)s"

#: oslo/vmware/exceptions.py:159
msgid "Resource already exists."
msgstr "La ressource existe déjà."

#: oslo/vmware/exceptions.py:164
msgid "Cannot delete file."
msgstr "Le fichier ne peut pas etre supprimé."

#: oslo/vmware/exceptions.py:169
msgid "File already exists."
msgstr "Le fichier existe déjà."

#: oslo/vmware/exceptions.py:174
msgid "File fault."
msgstr "Redirection fichier."

#: oslo/vmware/exceptions.py:179
msgid "File locked."
msgstr "Fichier verrouillé."

#: oslo/vmware/exceptions.py:184
msgid "File not found."
msgstr "Fichier non trouvé."

#: oslo/vmware/exceptions.py:189
msgid "Invalid power state."
msgstr "Status de démarrage non valide."

#: oslo/vmware/exceptions.py:194
msgid "Invalid property."
msgstr "Propriété non valide."

#: oslo/vmware/exceptions.py:199
msgid "No Permission."
msgstr "Pas de permission."

#: oslo/vmware/exceptions.py:204
msgid "Not Authenticated."
msgstr "Non authentifié."

#: oslo/vmware/exceptions.py:209
msgid "Entity has another operation in process."
msgstr "L'entité a une autre opération en cours."

#: oslo/vmware/exceptions.py:213
msgid "Duplicate name."
msgstr "Duplicat du nom."

#: oslo/vmware/exceptions.py:247
msgid "exception should be a subclass of VMwareDriverException"
msgstr "exception devrait être une subclass de VMwareDriverException"

#: oslo/vmware/image_transfer.py:167
#, python-format
msgid "Image: %s is in killed state."
msgstr "Image: %s est en état tué"

#: oslo/vmware/image_transfer.py:181
#, python-format
msgid "Image: %(image)s is in unknown state: %(state)s."
msgstr "Image: %(image)s a un statut inconnu: %(state)s. "

#: oslo/vmware/image_transfer.py:190
#, python-format
msgid "Error occurred while writing image: %s"
msgstr "Une erreur est survenue pendant l'écriture de l'image: %s"

#: oslo/vmware/image_transfer.py:275
msgid "Error occurred during file read-write task."
msgstr "Une erreur est survenue pendant la tache de lecture-écriture du fichier."

#: oslo/vmware/image_transfer.py:362
msgid "No image destination given."
msgstr "Pas d'image au sein de la destination donné."

#: oslo/vmware/image_transfer.py:379
#, python-format
msgid ""
"Error occurred during image transfer with reader: %(reader)s and writer: "
"%(writer)s"
msgstr ""
"Une erreur est survenue durant le transfère de l'image avec le lecteur: "
"%(reader)s et l'écriture: %(writer)s"

#: oslo/vmware/rw_handles.py:144
msgid "Could not retrieve VMDK URL from lease info."
msgstr "Impossible de récupérer VMDK URL depuis l'emplacement d'information."

#: oslo/vmware/rw_handles.py:201 oslo/vmware/rw_handles.py:340
#: oslo/vmware/objects/datastore.py:291
#, python-format
msgid "Invalid scheme: %s."
msgstr "Invalide schéma: %s"

#: oslo/vmware/rw_handles.py:213 oslo/vmware/objects/datastore.py:304
#, python-format
msgid ""
"Error occurred while creating HTTP connection to write to file with URL ="
" %s."
msgstr ""
"Une erreur est survenue pendant la création des connexion HTTP pour "
"écrire le fichier avec URL = %s."

#: oslo/vmware/rw_handles.py:227 oslo/vmware/rw_handles.py:371
#, python-format
msgid "Connection error occurred while writing data to %s."
msgstr "Erreur de connexion pendant l'écriture des données de %s"

#: oslo/vmware/rw_handles.py:235 oslo/vmware/rw_handles.py:379
#, python-format
msgid "Error occurred while writing data to %s."
msgstr "Une erreur est survenue pendant l'écriture des données de %s."

#: oslo/vmware/rw_handles.py:356
#, python-format
msgid ""
"Error occurred while creating HTTP connection to write to VMDK file with "
"URL = %s."
msgstr ""
"Une erreur est survenue pendant la création des connexion HTTP pour "
"écrire le fichier VMDK avec URL = %s."

#: oslo/vmware/rw_handles.py:509
#, python-format
msgid "Error occurred while opening URL: %s for reading."
msgstr "Une erreur est survenue pendant l'ouverture de URL: %s pour la lecture."

#: oslo/vmware/rw_handles.py:529
#, python-format
msgid "Error occurred while reading data from %s."
msgstr "Une erreur est survenue pendant la lecture des données depuis %s."

#: oslo/vmware/service.py:241
msgid "Error occurred while calling RetrievePropertiesEx."
msgstr "Une erreur est survenue pendant l'appelle RetrievePropertiesEx."

#: oslo/vmware/service.py:318
#, python-format
msgid "No such SOAP method %s."
msgstr "Pas de méthode SOAP %s."

#: oslo/vmware/service.py:324
#, python-format
msgid "httplib error in %s."
msgstr "httplib erreur dans %s."

#: oslo/vmware/service.py:328
#, python-format
msgid "requests error in %s."
msgstr "erreur de requetes dans %s."

#: oslo/vmware/service.py:339
#, python-format
msgid "Socket error in %s."
msgstr "Erreur de socket dans %s."

#: oslo/vmware/service.py:344
#, python-format
msgid "Type error in %s."
msgstr "Erreur de type dans %s."

#: oslo/vmware/service.py:347
#, python-format
msgid "Exception in %s."
msgstr "Exception dans %s."

#: oslo/vmware/objects/datacenter.py:23
msgid "Datacenter name cannot be None"
msgstr "Le nom du datacenter ne peut pas être \"vide\""

#: oslo/vmware/objects/datacenter.py:25
msgid "Datacenter reference cannot be None"
msgstr "La référence du datastore ne peut pas etre \"vide\""

#: oslo/vmware/objects/datastore.py:44
msgid "Datastore name cannot be None"
msgstr "Le nom du datastore ne peut pas etre \"vide\""

#: oslo/vmware/objects/datastore.py:46
msgid "Datastore reference cannot be None"
msgstr "La référence du datastore ne peut pas etre \"vide\""

#: oslo/vmware/objects/datastore.py:48
msgid "Invalid capacity"
msgstr "Capacité non valide"

#: oslo/vmware/objects/datastore.py:51
msgid "Capacity is smaller than free space"
msgstr "La capacité est plus petite que l'espace libre"

#: oslo/vmware/objects/datastore.py:79
msgid "datacenter must be set to build url"
msgstr "datacenter doit être initialiser pour construire url"

#: oslo/vmware/objects/datastore.py:163
msgid "Datastore name cannot be empty"
msgstr "Le nom du datastore ne pas etre \"vide\""

#: oslo/vmware/objects/datastore.py:168 oslo/vmware/objects/datastore.py:209
msgid "Path component cannot be None"
msgstr "Le chemin du composant ne peut pas etre \"vide\""

#: oslo/vmware/objects/datastore.py:222
msgid "Datastore path cannot be empty"
msgstr "Le chemin du datastore ne peut pas etre \"vide\""

